//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerfGun
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPoint
    {
        public int id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public string Party { get; set; }
        public Nullable<int> Strength { get; set; }
        public Nullable<int> Happy { get; set; }
        public Nullable<int> Friendly { get; set; }
        public Nullable<int> Talk { get; set; }
        public Nullable<int> Political { get; set; }
        public Nullable<int> Opinionated { get; set; }
        public Nullable<int> Votes { get; set; }
        public string Note { get; set; }
        public byte[] Voice { get; set; }
    }
}
